services:
  db:
    image: postgres:18.1-alpine
    restart: on-failure
    container_name: postgres_auth_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:8.4.0-alpine
    restart: on-failure
    container_name: redis_auth_app
    volumes:
      - ./.data/redis_data:/data
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    image: test_auth_app
    container_name: test_auth_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
