version: '3.8'

services:
  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    image: test_auth_app
    container_name: test_auth_app
    depends_on:
      - db